### ISSUE TITLE
AccessDeniedException for FSx client

### ISSUE THREAD

**Issue by puniomp** [aws-samples/scalable-medical-computer-vision-with-amazon-sagemaker#11]
ClientError: An error occurred (AccessDeniedException) when calling the CreateFileSystem operation: User: arn:aws:sts::498183134365:assumed-role/AmazonSageMaker-ExecutionRole-20211029T155214/SageMaker is not authorized to perform: fsx:CreateFileSystem on resource: arn:aws:fsx:us-east-1:498183134365:file-system/* because no identity-based policy allows the fsx:CreateFileSystem action

**Comment by michaelhsieh42** [comment]
Need to add policy described in [Adding permissions to use data repositories in Amazon S3](https://docs.aws.amazon.com/fsx/latest/LustreGuide/setting-up.html#fsx-adding-permissions-s3). It's added to the code and blog draft.
